export const INIT_FILES_START = 'INIT_FILES_START';
export const INIT_FILES_ERROR = 'INIT_FILES_ERROR';
export const INIT_FILES_SUCCESS = 'INIT_FILES_SUCCESS';

export const ADD_FILE_START = 'ADD_FILES_START';
export const ADD_FILE_SUCCESS = 'ADD_FILES_SUCCESS';
export const ADD_FILE_ERROR = 'ADD_FILES_ERROR';

export const DELETE_FILE_START = 'DELETE_FILE_START';
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
export const DELETE_FILE_ERROR = 'DELETE_FILE_ERROR';

export const EDIT_FILE_START = 'EDIT_FILE_START';
export const EDIT_FILE_SUCCESS = 'EDIT_FILE_SUCCESS';
export const EDIT_FILE_ERROR = 'EDIT_FILE_ERROR';
