export const AUTH_USER_START = 'AUTH_USER_START';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';

export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';

export const AUTH_USER_CHECK_START = 'AUTH_USER_CHECK_START';
export const AUTH_USER_CHECK_ERROR = 'AUTH_USER_CHECK_ERROR';
export const AUTH_USER_CHECK_SUCCESS = 'AUTH_USER_CHECK_SUCCESS';

export const LOGOUT_USER_START = 'LOGOUT_USER_START';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';
